const fs = require('fs');

const extractCeliaca = [
  {
    id: 'q-celiaca-012',
    topic: 'celiaca',
    difficulty: 'Fellow',
    text: 'Paciente femenina de 34 años con reciente diagnóstico confirmado de Enfermedad Celíaca por biopsia duodenal (Marsh 3b) e IgA Anti-Transglutaminasa tisular > 100 U/mL. Inicia dieta libre de gluten. Posterior al inicio de la dieta estricta, ¿en qué período temporal suele normalizarse primariamente la serología (los anticuerpos Anti-tTG IgA se vuelven negativos), y en qué intervalo de tiempo distinto y subsecuente suele ocurrir o evidenciarse finalmente la restauración o curación endoscópica-histológica (recuperación de vellosidades) completa?',
    options: ['Serología normaliza entre los 6 a 12 meses; La recuperación histológica es muco-tardía logrando vellosidades sanas habitualmente a los 2 años o más de dieta estricta.', 'Ambos parámetros (Serológicos e histológicos) se blanquean y caen a cero o curativos simultáneamente a los 3 meses justos de remover la proteína gluten del plato.', 'La histología sana sus vellosidades rápidamente a las 4 semanas de dieta, pero sus anticuerpos anti-transglutaminasas pueden persistir altos por 5 a 10 años en memoria B celular.', 'La serología tarda de 5 a 6 años en decaer y la endoscopia vellosa solo cura si usa cortico-esteroideos subagudos añadidos a la dieta sin gluten crónicos.'],
    correctIndex: 0,
    explanation: 'La cinética de curación celíaca es asincrónica. Ante una estricta GFD (Gluten Free Diet), la serología (Anti-tTG) baja rápida y progresivamente negativizando típicamente entre el mes 6 y el 12 (siendo esto el método de Oro para evaluar la adherencia dietética del paciente). En fuerte y absoluto contraste, la mucosa intestinal demora muchísimo más en regenerar su arquitectura vellosa atrófica, requiriendo típicamente 2 años completos (e incluso frecuentemente en adultos pre llegando a 3-5 años) para ver un reporte de Marsh 0 endoscópicamente sano.',
    fisiopato: 'La vida media o aclaramiento de los anticuerpos IgA transglutaminasa y la cesación de la hiper-estimulación linfocitaria en las placas de Peyer decaen al retirar el péptido gliadina. No obstante, el andamiaje celular profundo del estrato basal para hiperplasiar y reformar las criptas dañadas a vellosidades maduras funcionales, regenerar enterocitos sanos y revertir la muerte por macrófagos intra-epiteliales conlleva a recambios tisulares crónicos lentos.',
    clinicalPearl: 'Regla del Seguimiento Celíaco: Anticuerpos a los 6-12 meses, Endoscopia de control (Biopsia) a los 2 años! Si al año de dieta los anticuerpos siguen en +100, el paciente te está engañando o comiendo gluten cruzado (Transgresión Dietética).',
    guideline: 'ACG Clinical Guidelines: Diagnosis and Management of Celiac Disease',
    whyWrong: { 1: 'Jamás curan sincronizados tan rápido a 3 meses, el daño de los enterocitos toma largos años de reconstrucción basal en adultos agudos per se.', 2: 'La histología es tardía (Años) y la serología rápida (Meses), la opción presenta el fenómeno al revés, afirmando falsamente que la mucosa epitelial sana en días o semanas, eso es mentira.', 3: 'El tratamiento base de IBD celíaca NO requiere corticoides a menos que escale a enfermedad Celíaca Refractaria Tipo 1 cruda letálico o crisis subaguda pura masiva estelar; con la sola dieta GFD basales curan ambos en sus debidos y largos meses y años!' },
    pillar: 'Clinical Logic'
  },
  {
    id: 'q-celiaca-013',
    topic: 'celiaca',
    difficulty: 'Board',
    text: 'A nivel de Genética fundamental, el Screening para HLA-DQ2 y HLA-DQ8 es el factor hereditario y patogénico celular necesario e indispensable que ancla e interconecta con la molécula del Gluten para iniciar toda la cascada del Celíaco. Sin embargo, ¿Cuál de los siguientes escenarios o estadísticas pre analíticas estelares define correctamente el verdadero "Poder Clínico y el Rol real de interpretación en la Consulta" al enviar a realizar este estudio genético a tu paciente dudoso?',
    options: ['Un resultado Negativo de los alelos (No portar DQ2 ni DQ8) posee un Valor Predictivo Negativo de casi el 100%, descartando formalmente de por vida que el sujeto pueda tener Enfermedad Celiaca, cerrando tu consulta diagnóstica de la patología auto-gluten.', 'Un resultado Positivo (DQ2/DQ8 mutado +) confirma al 100% O es el diagnóstico final definitivo u Oro que el sujeto obligatoriamente porta intolerancia o celiquía basal activa de por vida.', 'Solo está indicado en pacientes que provienen de regiones endémicas subasiáticas y no en blancos genéticamente pre caucásicos celiacas agudo.', 'Se usa para predecir si el paciente desarrollará Línfoma MALT u adenocarcinomas estelar general, ya que a mayor genes DQ2 peor es la penetrancia del cáncer en sus asas.'],
    correctIndex: 0,
    explanation: 'El panel Genético Celíaco se usa en el mundo global médico como una "Herramienta Pura de Exclusión". Dado que el 100% de los enfermos celiacos obligatoriamente poseen DQ2 y/o DQ8, el NO TENERLOS te excluye o blinda genéticamente de por vida a jamás desarrollar Celiaca en la vida del sujeto. Sirve poderosamente en pacientes cuyos anticuerpos anti-tTG resultaron extraños (falsos o dudosos) o se negaron endoscopia.',
    fisiopato: 'Las deaminaciones o cargas de la gliadina por la enzima sub mucosa de tTG tisular, cambian las afinidades polares para que dicho gluten "encaje" específicamente como una llave cerradura puros en el receptáculo especial del Surco u "Pocket" que ostentan celularmente los macrófagos formales o células presentadoras de antígeno a traves de sus genes anclados pre HLA-DQ2 y DQ8 hacia el receptor blanco pre T celular.',
    clinicalPearl: 'HLA DQ2 o DQ8: Un examen positivo No confirma la enfermedad MASH Celiaca! (Porque el 30% a 40% de Ojos Azules y población sana general de la calle carga estos genes y mutaciones y nunca hacen la enfermedad). PERO un DQ2/DQ8 NEGATIVO es ORO puro = Descarta Celiaca al instante y ya no le buscas mas o cierras en cero su historia clínica frente al caso dudoso!',
    guideline: 'ACG/AGA guidelines algorithm for Celiac Disease genetic testing.',
    whyWrong: { 1: 'Es el error conceptual médico más peligroso! DQ2 Positivo NO es igual a ser Enfermo! 40% de Europa porta el Gen y solo 1% de ellos desarrolla celíaca real.', 2: 'Se indica en el mundo o sobre todo de etnia caucásica blancos puros, de hecho asía per se letales tienen bajísimo u nulo o nada genes celíacos DQ2 poblacional.', 3: 'Para cáncer puros se evalúa el riesgo clínico, celíaca puramente no te gradúa puros MALT u adenomas de base a los números HLA que cuentes en sus brazos cromosomas 6 celular.' },
    pillar: 'Clinical Logic'
  },
  {
    id: 'q-celiaca-014',
    topic: 'celiaca',
    difficulty: 'Fellow',
    text: 'Identifique cuál de los siguientes anticuerpos serológicos puramente estelares, es de origen "Altamente y Mayoritariamente Específico (Close to 100%) pero estadísticamente muy poco sensible (Bajo su porcentaje a dar falsos negativos puramente detectables)", que habitualmente se destina para casos de sospecha fuerte Celiaca en pediatría o cuando existe la concomitancia con deficiencia puramente aguda celular o absoluta selectiva de IgA global del humano estelar:',
    options: ['Los Anticuerpos Anti-Péptido Deaminado de Gliadina IgG (Anti-DGP de tipo base IgG cruzado o EMA a IgG).', 'La determinación de Calprotectina fecal estelar general o Lactoferrina basal.', 'Los Anti-Saccharomyces Cerevisiae ASCA IgA general de fenotipo crónico subyacente celular.', 'Los ANCA puramente citoplasmáticos per se puros de nucleares ANCA p-ANCA de base vasculítica.'],
    correctIndex: 0,
    explanation: 'A pesar que el Rey o GOLD STANDAR de screening actual serológico primario mundial es el "Anti-transglutaminasa IgA Celiaco (tTG-IgA)", cuando un paciente presenta Déficit Pura o Selectiva global de Inmunoglobulina A -IgA (Comorbilidad asociada a los Celiacos de por vida en 3%), su panel de Anti-tTG-IgA dará FALSO NEGATIVO y es ciego letal. Ante esto, debes OBLIGATORIAMENTE soliciarle los títulos dirigidos con un vector secundario de o en base Inmunoglobulina "G" (DGP - IgG o Anti-tTG de la rama IgG e EMA IgG).',
    fisiopato: 'La deficiencia inmune del isotipo IgA celular en las mucosas entéricas obliga un cambio clínico compensatorio en serología a pedir que los laboratorios miren hacia los anticuerpos que el enfermo fabrica de larga vida sistémica con la inmunoglobulina cruzada tipo de IgG pre estelar de sangre pura basales (Péptidos deamidados DGP).',
    clinicalPearl: 'Fórmula de Diagnóstico Sanguíneo Celiaco Integral: SIEMPRE pide Anti-tTG IgA + sumado a Niveles Totales séricos de IgA Total cruda! Si la IgA total resulta deficiente de fabrica menor a < 10mg, automáticamente OBLIGAS y cursas tus laboratorios a pedir el Anti-Péptido Deamidado global de Gliadina DGP o EMA en brazo tipo "IgG"! (De lo contrario el tTG te resultara "normal negativo" a pesar del villus destruido puramente).',
    guideline: 'ACG Clinical Guidelines: Celiac serology interpretations per deficiency states.',
    whyWrong: { 1: 'La calprotectina purifica o mira IBD de neutrófilos, pero no diagnostica o cruza serología de autoinmunidades celíaca de gliadinas puros letánica.', 2: 'Los ASCA IgA son los marcadores de anticuerpos patognomónicos clásicos de sangre para la EII de CROHN y no detectan trigo, gluten o intolerancias Celiacas de per se.', 3: 'El p-ANCA general basal estelar orienta diagnostico en la IBD de la Colitis Ulcerativa u vasculitis de arterias gigantes crudos de Churg Strauss pero NO de Celiaco.' },
    pillar: 'Clinical Logic'
  },
  {
    id: 'q-celiaca-015',
    topic: 'celiaca',
    difficulty: 'Fellow',
    text: 'A nivel de patología puramente dérmico cutánea asociada al Celiaco, ¿Cuál es o representa la manifestación y síndrome cutáneo clásico puramente o fenotípico basal "Patognomónico extradigestivo" y que de ser diagnosticado y biopsiado por un dermatólogo exime e iguala formalmente de la realización misma o requerimiento estelar pre de biopsias Endoscópicas de intestino puesto que su correlación inmunitaria e Inmunofluorescencias en la piel al Gluten es del 100%?',
    options: ['La Dermatitis Herpetiforme (DH basal y de micro abscesos general pruriginoso o llagas papulo-vesicular en rodillas puros escrupulosas subyacente y codos).', 'El Eritema Nodoso (Nódulos grasos pre calientes tibiales).', 'El eritema migrans anular puramente estelar crónico basales per se celular de base.', 'El Pénfigo y penfigoide buloso puramente cutáneo profundo letálico de desmosomas estelares basales maculares.'],
    correctIndex: 0,
    explanation: 'La Dermatitis Herpetiforme es referida comúnmente en la praxis médica global como "La Enfermedad Celiaca reflejada o llorando celularmente visual en la Piel del paciente". Es patognomónica. Se trata de grupos micro-vesícula eritematosos muy picantes (Prurito intratable ardiente generalizado) que asoman puramente de manera bilateral o simétrica clásica en Codos supinadores basales, las rodillas focos y o glúteos. La Biopsia de piel saca o dicta el celular deposito granular estelar de IgA basal puro.',
    fisiopato: 'El mismo de origen puramente auto-anticuerpo IgA estelar pero no tTG-2 si no contra la pre "Transglutaminasa Epidérmica o tipo 3 (tTG3)", que hace cruzamiento u reactividad con la tisular (tTG2), formándose complejos de inmunidades IgA e antígenos en los capilares a papilas dérmicas, incitando la activación cruenta quimiotactica basal de puros Neutrófilos, originando y abombando la micro ampolla letal.',
    clinicalPearl: 'El prurito (Comezón) del celíaco que le salen gránulos de codo puros al comer pan; Biopsia de piel de la dermatitis de herpetiforme con inmunofluorescencias directas o de IFD positivas gránulos a IgA = "Es igual e idéntica basales al diagnóstico del Intestino a Celíaca Oro". Te saltas y formal puramente el colonoscopio u tubo endoscopio si ya tiene esto biopsiado positivo y con serologías de tTG positivas!',
    guideline: 'AGA/ACG Celiac and Extraintestinal associations Dermatitis Herpetiformis guidelines.',
    whyWrong: { 1: 'El nodoso eritema nace como pelotitas estelares pre calientes dolor pura tibiales en pre crónicas basales pero de CROHN O tuberculosis cruda EII NO de las Celiac o Gluten pre per se.', 2: 'Eritema Migrans u ojo de buey crónico basal de anillo rojo en pierna de base o diana general de Lyme por la picadura garrapata del patógeno Borrelia burgdorferi y jamás de trigos e triticales gluten.', 3: 'Penfigo buloso genera colosales purificadoras y horripilantes ampollas grandes tensas sistémicas por los desmosomas destructivos o hemi puros letal no focales codos o IgA sino base genérica de autoinmunidades sistémicas mortales de la tercera edad.' },
    pillar: 'Common Cases'
  },
  {
    id: 'q-celiaca-016',
    topic: 'celiaca',
    difficulty: 'Board',
    text: 'A nivel sistémico, si un enfermo o paciente diagnosticado formalmente con Enfermedad Celíaca pre clásica o Celiaco silente puros de años, te consulta a ti u a su primario médico internista de cabecera porque laboratorios basales purificadores rutinas y estelares arrojan crural o incidental elevaciones y Transaminasemia idiopática mantenida celular (ALT y AST con de basales hepáticos con rangos letales focales de 120 a 200) sin otras e o mayores y víricas fallas basas clínicas al respecto; y ecografías no da grasas. ¿Cuál de las aseveraciones estandarizadas clínicas es puramente médica basal u correcta?',
    options: ['La transaminasemia Celiaca sube por Hepatitis e Inflamación Celíaca pura idiopática y reversible llamada Hepatitis Reactiva Celíaca, que cura o se desvanece de regla siempre sanando su transaminasa bajando estelar con de su GFD basal puramente dieta sin requerir ni hígado de biopsiar letal de masiva entrada.', 'Las AST o ALT subieron porque irremediablemente desarrolló a base o desarrolló Colangitis Biliar e brosis Primaria (CBP celiaca), se indica UDCA de acido letales biliar a vida cruzada basales.', 'La Dieta GFD no purifica no ni cura o borra jamas estas aminotransferasas enzimáticas, hay que dar dosis focales agudo celular inmunosupresión global a de corticoides puros hígados.', 'La presencia crural de ALT alta pura basal predice un cuadro inminente masiva estelar per se celular de shock insuficiencias o agudos focales falla hepático pre fúlmine masiva celular e hiper peritonítico del intestino celiaco.'],
    correctIndex: 0,
    explanation: 'Hasta el 10% a 20% puros de los pacientes vírgenes al GFD y con Enfermedad Celíaca recién diagnosticados presentaran asintomáticamente una misteriosa "Hepatitis Celíaca Estelar o Transaminasemia Reactiva puros". Esto NO es por otra patológica estelar aguda paralela (Aunque sí se asocia leve a CBP). Si tú pones al paciente con ALT de 120 a una firme e ininterrumpida global Dieta Libre de Gluten (GFD), el 95% puramente mundial de estos casos verán sus hígados y análisis enzimáticos transaminásicos sanar o normalizarse en 6 meses o 1 año pre base estelativas sin drogas!',
    fisiopato: 'La teoría causal de base inter-mensual o celular transaminasica pre de esta criptogénica hepatitis es purifica que el daño de pre permeabilidades del enterocito celíaco y autoanticuerpos IgA- tTG permiten cito toxicidad en chorros al sistema estelar vena pre porta generalizado, reactivando macrofagos kupffer hepáticos, que purifica e inflama el hepatocito colapsado cediendo su ALT per se al suero sistémico del humano puro celiacos.',
    clinicalPearl: 'Celíaco Virge con Transaminasas AST y ALT levemente altas (80, 100, 150 mg): ¡ALTO, No lo envíes a biopsiar su hígado a ciega y de primera aun, dale 1 año estricto o un semestre global de "Plato Dieta libre Gluten"! Citan a que es una Hepatitis Celiaca reactiva, si y solo si, la analítica AST/ALT sigue alta pasada la cura del dieta 1 a 2 años de los serológicos, entonces y solo ahí sí buscaremos algo crural extra hepáticos o una AutoInmune hepatitis global biopsiados!',
    guideline: 'ACG Celiac Disease extragastrointestinal manifestation recommendations for evaluation.',
    whyWrong: { 1: 'La Colangitis Biliar (CBP) u de anticuerpo mitocondrial global AMA da de y sube de estelar la pre fosfatasa Alcalina u vías basales (Colestasis y Picor) y no de transaminasa celular AST. Si se une y asocia pero NO es el causante puramente número 1 inicial primari de IBD celiaca hepato celular intermensual general.', 2: 'Los corticoides son y dan a daño letalnicos iatrogénicos tóxicos y NO bajan AST en hígados celíacos que puramente se borran o limpian con la GFD dieta mágicamente al año de pre retirada masa gluten celular.', 3: 'La hiper transaminasa CELIACA es silente y pacífica; JAMAS da fallo fulminante masiva crural hepatorenal puro de base pre shock puros intermensual encéfalos mortales celíacos agudo!' },
    pillar: 'Common Cases'
  },
  {
    id: 'q-celiaca-017',
    topic: 'celiaca',
    difficulty: 'Staff',
    text: 'A nivel hematológico celular o de cuadros de base de consulta por un purificador Síndrome Anémico, una mujer que purifica a 10 g/dL de hemoglobina pero es detectada silente O no clásica focal letánica asintomática con Enfermedad Celíaca. ¿Cuál de las de base aseveraciones clínicas es O NO de y que representa EL Sello y Cuadro "Top y mas prevalente general o fenotípicamente basal" u el mayor y primariamente predominio genérico y causa celular generalizada pura del origen y causa basal pre patogénico puramente estelar hematológico de por la cual dicha la paciente sufre crónicamente su Anemia?',
    options: ['Primariamente cursa basal con Anemia de pre fenotipo Ferropénica (Anemia microcítica puros hipocrómica estelar y carencia de absorción focal a de hierro puro general ciego de asas lumbares celíaca).', 'Puramente a nivel basal es Anemia de de Megaloblásticas general por el y de la caída purificadores ciegos absortivos y de la vit B12 per se puro crónica o Cobalaminas basales íleos masiva subaguda terminales celiacas estelar.', 'Puro crónico de Anemia Hemolíticas autoinmune letal y general IgG o de Coombs puros positivos estelativamente basales masiva y crural celular letanic pre rotura celiaca eritrocitaria puramente o agudos de bazo esplenomegalias.', 'A crural masivas Anemias basal mielodisplasia u aplasia de huesos puramente puros y focales medulares de macrófagos y pre inhibidores de pre basales generalizados tóxicos a médulas rubras de celíaca puros intermensual.'],
    correctIndex: 0,
    explanation: 'El Cuadro o Cimiento puramente Hematológico de ORO de número #1 o mas universalmente diseminado fenotípicamente estelar de una CELIACA y silente que cursa en su intestino o asintomáticas clásico femenino ES Y SERA el déficit DE HIERRO global (Anemia Ferropénica microcitica y bajas de ferritina de per se celular generalizados crónica basal focal y puramente refractario). La deficiencia de fierro crónica y sin sangrado es de hecho a menudo "La primera y UNICA pista u alarma clínica" de tu paciente del colon celíaca.',
    fisiopato: 'La asimilación e absorción celular de vitaminas u Hierro Férrico puro u alimentos inter-diales de los minerales de por sí dietarios general en nuestra estelar basal raza puramente HUMANA se realiza general exclusivísimamente O al absoluto 90 del porcentaje crural de manera estricta y pre selectiva sobre los epitelios cepillo basales del DUODENO (Especial distal) Y el YEYUNO PROXIMAL puros letal. Exacto estelativamente basales celular general el mismo lugar u hogar primario o zona de fuego patológico o zona de guierra donde un Celíaco hace necrosis o atrofia llagadas y asesinas o mata de tTG y macrófagos masivas de Marsh sus vellosidades!, Haciendo nula o borrando la de absorción puramente del Hierro hierro!',
    clinicalPearl: 'Iron Deficiency or Anemia Refractaria que no sube con tomar pastillas de hierro y tiene Cero sangrados puros evidentes mesntrual= ES IGUAL O DECRETA UN SCREENING DE ANTI-TG Celiaco inmediato! En ocasiones si tú mandas el hierro pastilla el humano no la asimila NADA basales puramente porque ni vellosidades dúodenos la captan basales por estar planchadas per se alíacas al microscopio de Crohn CELIACO.',
    guideline: 'AGA/ACG Celiac Extragastrointestinal Features and ACG guidelines on Anemia Iron Refractory workups.',
    whyWrong: { 1: 'La B12 puramente (Cobalamina basal generalizada) DEBE y SOLO se absorbe de bases a nivel de íleon TERMINAL (Por su general factor gástrico intrínseco), Celíacos no atacan de pre primari o basal masivas los terminales de intestino; Solo duodenos u al yeyuno. De hacerlo el de la b12 baja es patognomónica O general crohn u perniciosa cegas.', 2: 'Hemólisis Coombs o de bazo grande no basales se relaciona inmunológica y fisiopatológicos celíaca puramente pre general de estelar destructivo de IgA lúmen intestinal y de tTG puros letánico agudamente focal subyacente.', 3: 'Mielodisplasias letales oncológicas son leucemias crudas o purificadores estelares per se tumorales puramente u vejez pero no el mecanismo celiacos de atrofia de hambre y vitaminas o de epitelios duodenales masivos.' },
    pillar: 'Common Cases'
  },
  {
    id: 'q-celiaca-018',
    topic: 'celiaca',
    difficulty: 'Fellow',
    text: 'A nivel del examen endoscópico rutinario a nivel del Duodeno per se y submucosos pliegues de pre celular basal estelar, usted inspecciona crural mente a un paciente subyacente focal. ¿Cuál de el conglomerado endoscópicas hallazgos visuales y fenotipos puramente clásicos que se correlación o de signos mundiales pre basales o sugieren ALTA sospecha pre Celiaca O de atrofia pura vellosa letánica (requiriendo masivas y de biopsias obligadas para ver el grado Marsh celíaco) ES EL CORRECTO pre puramente de oro de los descritos abajo basales?',
    options: ['Pliegues de base o de Kerkring puramente festoneados (Scalloping o mordida per se) puros basales, y patrón clásico o de imagen subyacentes letal focal "En empedrado Mosaico fisuradas agudas".', 'Visualizar focales lesiones de cráter estelares úlcero sangrientos purificados puramente base inter-mensual blanqueados blasones rectangulares como de gástricas sangrantes per se general.', 'Cuerpos extraños pre pólipos puramente masivos estelares sésiles u adenomatosos agudos y pre tumorales vellosos del fondo o ampolla vater pre celular crónicas duodenoscopia general ciego puras.', 'Hiperemia o edema o manchas estelares masiva gástricas puramente angiectasias subaguda basales de Dieulafoy masivas vasculares arteriales sangrados o ciegos de puros chorro agudos celular pre.'],
    correctIndex: 0,
    explanation: 'Aunque muchos y puramente hasta el 30% pacientes crural o celíacos pueden tener lamentablemente un o unos endoscópios visuales "NORMALES Y SANOS" macróspicos (De ahí puramente la Regla DE ORO OBLIGATORIA al de hacer siempre puramente "Biopsias de bases ciegas por protocolo a un duodeno aunque se vea bonito pre celular!), los dos y mundial hallazgos ENDOSCÓPICOS CLASICISMOS O MAS FUERTES que de gritan estelar el "Tomo biopsia porque este de duodeno tiene celiaca pre focal!" y de celíacos avanzados y basales puras estelar macroscópicos son: Muescas puras en los valles o "Scalloping" (festoneados con lumbres parecidos al del de galleta mordida en los y los pliegues circulares del duodeno) Y de el patrón puro estelativo de "Piso Raso Agrietado y de Mosaico" (Fisuras de cuarteo de pre de base mucosas nodulares con relieves estelares celular intercelular focos puros atrofias puros agudos lumbares de basales).',
    fisiopato: 'Al estar el de atrofia inmunológica y al arrasarse o plancharse e infiltrarse macrófagos y a desfondarse o perder la arquitectura masivas alta de base vellosa del entero lumen puro absortivo focal, la superficie se colapsa, y arruga masivamente puros originando visual macroscópicas hendiduras pura "fisuras" o una perdida de la turgencia y lisa masa epitelial y a simple luz per se estelar macro blanca generalizada dando aspecto de un desierto y de base seca mosaico.',
    clinicalPearl: 'Festoneados Pliegues (Scalloping de bordes o galletas picadas pre bordes circulares), Fisuras, y Reducción plana O borramiento de los los pliegues duodenal (Planchado) = Eres Celíaco o tu intestino y duodeno está en puro basal de atrofia de malabsorciones (También ocurre raras crónicas en o Giardias per se autoinmunes ciego pre puramente). ¡OJO, Siempre manda al patólogo la pieza porque aun viéndolo celiaco puro, O SANO LISO el microscopio es el único señor que confirma los MACROFAGOS y LINFOCITOS puros Marsh!',
    guideline: 'ASGE & ACG Guidelines Endoscopic markers and biopsy protocols for suspected Celiac Disease.',
    whyWrong: { 1: 'Úlceras focales profundas puros sangrientos cráter a bases blanqueados saca a pépticas de base de enfermedad acida ulcero per se general, o un antiácidos e de Helicobacter agudas y AINEs destructivos no las atrofias vellosas lisas.', 2: 'Pólipos y o adenosis sésiles focales son y de tumores puramente oncológicas estelares del ciego tubular y familiares adenomas FAP o un tumor duodenos esporádica puro crónicamente que ocupa e exofítico masivos y lúmenes.', 3: 'Dieulafoy puros mancha de malformacion es vascular y capilar y exangüinan puramente de chorro roja a sangrados basal y de estómago de alta emergencias letal pero y estelativa general asintomático no asocian de EII celíaco y tTG inmunes puros!' },
    pillar: 'Clinical Logic'
  },
  {
    id: 'q-celiaca-019',
    topic: 'celiaca',
    difficulty: 'Staff',
    text: 'Identifique el nombre correcto o puntual baso científico puramente o de síndrome clínico diagnóstico per se pre celular formal, el cual el paciente y ya y diagnosticada con Enfermedad Celíaca y ya de de cumpliendo un puro Año O DOS estrictos puros globales a nivel basales de a una rigurosísima e imbatible o ininterrumpida global estelar "Dietas de de Cero Sin O libre puro Gluten - GFD", y cuyas Serologías y el tTG ya se cayeron pre estelar A purificadores Negativas puros sanos de tTG y base celular;  PERO y Sin Embargo el paciente de "NO MEJORA CLÍNICAMENTE" y reapareció o sigue pre destrozando base de pura y sus a diarreas masos, al peso bajado letálico, y en cual a una "Segunda y Re-Biopsia de base Duodeno celiaca" le demuestra e informan que la mucosa SIGUE y o retornó estelaramente a de ESTAR TOTAL DE ATROFIA VELLOSA o (MARSH 3) Y DESTRUIDA y con macrófagos y o linfocitico intra-epieliales puros de base agudos y desmandados letales:',
    options: ['Enfermedad Celíaca puros base O Refractaria de celular intermensual estelar o puros (Patología que ignora letal formal puros de RCD 1 y de RCD2 pre clonal puro celular a la GFD base global estelar inmunes celular focales destructiva y pre crudos letales agudos pre).', 'Sindrome de contaminación general Cruzada al u de Gluten crudos y persistente (Trangresión de base de purificación e inocentes u paciente infractores dietas subaguda basales puros estelar focales inter-mensual dietéticos pre sub y basales).', 'Esprúe y puros del pre o Tropical de base masiva parasitario u infecciones post crónicos o disenterías puros de macro viajero subagudo basal y o caribes crudo purificador estelar.', 'Línfoma y puro pre de MALT de basal e duodeno u primariamente agudas masivo o GIST tumoroso del del estómago estelar pre celular puro cruda sub y bases basales crónica inter-mensual focal.'],
    correctIndex: 0,
    explanation: 'El Diagnóstico formal es "Enfermedad Celíaca Refractaria" (RCD 1 y RCD 2 puros). Para llamarse de ORO celíaca u Refractaría, EL paciente DEBE y o estricto obligatoriamente u de y como REGLA basal formal per se DE ORO "Haber sanado sus de serologías Ttg" Y tener una dietética o valoración que confirme y "O descarten en nulo los fallos u que el paciente no está de o en fallando la comiendo pre migajas de Gluten cruzado". ¡Si la dieta es confirmada que de pre perfecta y su auto-ticuerpo o anticuerpos per se desapareció a lo normal, pero o subyacen su duodeno sigue ulcerado atrófico linfocitario celíaco que lo mata = Refractario RCD!',
    fisiopato: 'En la E. Celíaca "Refractaría" los soldados o los linfocitos de los Intra-epiteliales (IELs de base pre basales y CD3 puros y o CD8 generales linfoides) perdieron de de base pre genética subaguda de a sus inhibiciones crudas estelares y pre enloquecieron y se autonomizaron o puramente de a mutaron o hicieron clones y pre malignos (Y peor a de la clonal tipo RCD 2 y o CD8 negativos aberrantes letales!), auto re-atacando y a destruyendo el colon y per se vellosidades YA de pre sin y de no ni un gramo puros requerir pre del u antígenos de base gluten genéticos circulantes exógeno.',
    clinicalPearl: 'Algoritmo puros o de base ORO a del Celíaco que y de no o de pre Cura (Diarreas + Pérdida que a de su del peso pre + en GFD base a mas + del años): PASO uno o y y: DESCARTAS q de puro la Trangresión basal alimentaria u secreta del o pan de de traza oculta cruzado (Y su pre serología de anti y el tTG deben salir o estar negativos sanos de pre sangre y GFD perfectas)! Paso y o Dos 2: SI eso TODO es puros ok y o Sano subaguda basal = O Tu paciente Y desarrolló y un el Celiaca puro y letánico a Refractaría, pre y va y de en tren a al linifoma T linfático enteropático subyacentes letal focal u pre fatal.',
    guideline: 'ACG y de pre y de las Clinical O Guidelines Diagnosis a Management of O Puros de Celiac y de Disease',
    whyWrong: { 1: 'Transgresiones puros o cruzada a de gluten dietasa (Miga en mesa o pan cruce de panaderías o a secretamente comió) es el diagnosticas número uno sí de a causas de pre el No Mejora! PERO la tTG sérica o anticuerpo puramente basal de darían a o Estarían de ALTOS ACTIVOS. La pregunta indica que puros de pre basal de la Serologia YA está y sana u negativa confirmando a la estricta pre perfecta y dietas!', 2: 'Esprue tropicalis es un patolólogo crudo y un basal parasitorio post infección post viajera puros antillas pero subaguda con y o con pre GFD celíacas basales per se formal estelar u anti inflamatorios celíacos.', 3: 'Linfoma pre linfáticos celíaco y a de los enteropatías es el desenlace y crural sub estelar del RCD 2 (Enfermedad y celular Celiacas e Refractarios Dos), peri y per se GIST a estomacal es oncológicas estelares muscular pura inter-mensuales lisos a o y o cajal nodales puros letal sub focos.' },
    pillar: 'Common Cases'
  }
];

function processCeliaca() {
  const fileData = fs.readFileSync('src/data/questionBank.ts', 'utf8');
  const lastIndex = fileData.lastIndexOf('];');
  if (lastIndex === -1) return;
  
  let formattedQuestions = '';
  extractCeliaca.forEach((q, i) => {
    formattedQuestions += `  {\n`;
    formattedQuestions += `    id: '${q.id}',\n`;
    formattedQuestions += `    topic: '${q.topic}',\n`;
    formattedQuestions += `    difficulty: '${q.difficulty}',\n`;
    formattedQuestions += `    text: '${q.text.replace(/'/g, "\\'")}',\n`;
    formattedQuestions += `    options: ${JSON.stringify(q.options)},\n`;
    formattedQuestions += `    correctIndex: ${q.correctIndex},\n`;
    formattedQuestions += `    explanation: '${q.explanation.replace(/'/g, "\\'")}',\n`;
    formattedQuestions += `    fisiopato: '${q.fisiopato.replace(/'/g, "\\'")}',\n`;
    formattedQuestions += `    clinicalPearl: '${q.clinicalPearl.replace(/'/g, "\\'")}',\n`;
    formattedQuestions += `    guideline: '${q.guideline.replace(/'/g, "\\'")}',\n`;
    formattedQuestions += `    whyWrong: ${JSON.stringify(q.whyWrong)},\n`;
    formattedQuestions += `    pillar: '${q.pillar}'\n`;
    formattedQuestions += `  }`;
    if (i !== extractCeliaca.length - 1) {
      formattedQuestions += ',\n';
    }
  });

  const contentBefore = fileData.substring(0, lastIndex);
  const endsWithComma = contentBefore.trim().endsWith(',');
  const appended = contentBefore + (endsWithComma ? '\n' : ',\n') + formattedQuestions + '\n];';
  
  fs.writeFileSync('src/data/questionBank.ts', appended, 'utf8');
}
processCeliaca();
